### ISSUE TITLE
Cannot import RDC file

### ISSUE THREAD

**Issue by Darrefull** [eliemichel/MapsModelsImporter#109]
Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps or Google Earth web
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
Console log is accessible in Windows > Toggle System Console (right click to copy).

 - The .rdc file:
https://drive.google.com/file/d/16D2-ssQOlD4V5I1969i5SC9suxt5ANU1/view?usp=sharing
 - Your GPU name:
AMD Radeon RX 560X / Radeon Vega 8
 - Version of this add-on (must be the most recent one):
0.3.3
 - Version of RenderDoc (1.10 recommended):
1.10
 - Version of Blender (2.82 minimum):
2.90.1
- Version of Chrome:
86.0.4240.198
 - Command for chrome:
C:\Windows\System32\cmd.exe /c "SET RENDERDOC_HOOK_EGL=0 && START "" ^"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe^" --disable-gpu-sandbox --gpu-startup-dialog --use-angle=gl"
- Screenshots:
https://prnt.sc/vktty2
https://prnt.sc/vktu7u
https://prnt.sc/vktwmd
- Error from console:
```
globUniforms:
  _uA: [1487.4779052734375]
  _uB: [1904.0]
  _uC: [0.800000011920929]
  _uD: [1.0]
  _uE: [0.0]
  _us: [-1.476313514103822e-06, 0.1545681655406952, 1.74947331288422e-06, -114.52738189697266, 0.19967898726463318, -8.563032452002517e-07, 0.24115179479122162, -159.01002502441406, -0.07657948136329651, -1.443520886823535e-06, 0.06255379319190979, 122.29776763916016, -0.07655315846204758, -1.4430246437768801e-06, 0.06253229081630707, 137.31820678710938]
  _ut: [[1.0], [1.0], [0.0], [1.0], [0.0], [0.0], [0.0], [0.0]]
  _uw: [0.5, -255.5, 0.00390625, -0.00390625]
  _ux: [0.09911692142486572]
```
